import type { SubjectPack } from './types';

export const SUBJECT_PACKS: SubjectPack[] = [
  {
    id: 'cat-care',
    name: 'Cat Care Basics',
    icon: '🐱',
    description: 'Learn essential cat care, grooming, and health tips for happy kitties.',
    questions: [
      {
        id: 'cc1',
        type: 'mcq',
        category: 'Nutrition',
        text: 'Which food is dangerous for cats?',
        options: [
          { id: 'a', text: 'Cooked chicken' },
          { id: 'b', text: 'Wet cat food' },
          { id: 'c', text: 'Chocolate & garlic' },
          { id: 'd', text: 'Plain rice' },
        ],
        correctOptionId: 'c',
      },
      {
        id: 'cc2',
        type: 'mcq',
        category: 'Behavior',
        text: 'Why do cats purr?',
        options: [
          { id: 'a', text: 'Only when happy' },
          { id: 'b', text: 'To self-soothe or show comfort' },
          { id: 'c', text: 'To communicate hunger only' },
          { id: 'd', text: 'It is purely involuntary' },
        ],
        correctOptionId: 'b',
      },
      {
        id: 'cc3',
        type: 'mcq',
        category: 'Senses',
        text: 'What helps cats navigate in low light?',
        options: [
          { id: 'a', text: 'Their loud meowing' },
          { id: 'b', text: 'Whiskers and tapetum lucidum' },
          { id: 'c', text: 'A strong sense of taste' },
          { id: 'd', text: 'Color vision' },
        ],
        correctOptionId: 'b',
      },
      {
        id: 'cc4',
        type: 'pair',
        category: 'Behavior',
        text: 'Match each cat behavior to its meaning!',
        pairs: [
          { left: 'Slow blinking', right: 'Sign of trust & affection' },
          { left: 'Tail puffed up', right: 'Feeling threatened or scared' },
          { left: 'Head bunting', right: 'Marking you as safe territory' },
          { left: 'Chattering teeth', right: 'Excitement watching prey' },
        ],
      },
      {
        id: 'cc5',
        type: 'mcq',
        category: 'Health',
        text: 'How often should cats typically visit a vet?',
        options: [
          { id: 'a', text: 'Only when visibly ill' },
          { id: 'b', text: 'Every 5 years' },
          { id: 'c', text: 'At least once a year' },
          { id: 'd', text: 'Every month' },
        ],
        correctOptionId: 'c',
      },
    ],
  },
  {
    id: 'web-basics',
    name: 'Web Dev Basics',
    icon: '💻',
    description: 'HTML, CSS, JavaScript fundamentals for budding web developers.',
    questions: [
      {
        id: 'wb1',
        type: 'mcq',
        category: 'HTML',
        text: 'Which HTML tag is used for the largest heading?',
        options: [
          { id: 'a', text: '<h6>' },
          { id: 'b', text: '<heading>' },
          { id: 'c', text: '<h1>' },
          { id: 'd', text: '<title>' },
        ],
        correctOptionId: 'c',
      },
      {
        id: 'wb2',
        type: 'mcq',
        category: 'CSS',
        text: 'Which CSS property controls text size?',
        options: [
          { id: 'a', text: 'font-weight' },
          { id: 'b', text: 'text-size' },
          { id: 'c', text: 'font-size' },
          { id: 'd', text: 'letter-size' },
        ],
        correctOptionId: 'c',
      },
      {
        id: 'wb3',
        type: 'pair',
        category: 'Concepts',
        text: 'Match each web term to its correct description!',
        pairs: [
          { left: 'HTML', right: 'Structure & content' },
          { left: 'CSS', right: 'Styling & layout' },
          { left: 'JavaScript', right: 'Interactivity & logic' },
          { left: 'API', right: 'Interface for data exchange' },
        ],
      },
      {
        id: 'wb4',
        type: 'mcq',
        category: 'JavaScript',
        text: 'Which keyword declares a constant in JavaScript?',
        options: [
          { id: 'a', text: 'var' },
          { id: 'b', text: 'let' },
          { id: 'c', text: 'static' },
          { id: 'd', text: 'const' },
        ],
        correctOptionId: 'd',
      },
      {
        id: 'wb5',
        type: 'mcq',
        category: 'CSS',
        text: 'What does "flex" in CSS Flexbox refer to?',
        options: [
          { id: 'a', text: 'A font style' },
          { id: 'b', text: 'A layout model for arranging items' },
          { id: 'c', text: 'An animation property' },
          { id: 'd', text: 'A grid system only' },
        ],
        correctOptionId: 'b',
      },
    ],
  },
  {
    id: 'space-science',
    name: 'Space Science',
    icon: '🚀',
    description: 'Explore planets, stars, and the wonders of the cosmos.',
    questions: [
      {
        id: 'ss1',
        type: 'mcq',
        category: 'Solar System',
        text: 'Which planet is known as the Red Planet?',
        options: [
          { id: 'a', text: 'Venus' },
          { id: 'b', text: 'Jupiter' },
          { id: 'c', text: 'Mars' },
          { id: 'd', text: 'Saturn' },
        ],
        correctOptionId: 'c',
      },
      {
        id: 'ss2',
        type: 'mcq',
        category: 'Stars',
        text: 'What type of star is our Sun?',
        options: [
          { id: 'a', text: 'Red Giant' },
          { id: 'b', text: 'Yellow Dwarf' },
          { id: 'c', text: 'White Dwarf' },
          { id: 'd', text: 'Neutron Star' },
        ],
        correctOptionId: 'b',
      },
      {
        id: 'ss3',
        type: 'pair',
        category: 'Planets',
        text: 'Match each planet to its key feature!',
        pairs: [
          { left: 'Saturn', right: 'Famous for its rings' },
          { left: 'Jupiter', right: 'Largest planet in solar system' },
          { left: 'Neptune', right: 'Farthest from the Sun' },
          { left: 'Mercury', right: 'Closest planet to the Sun' },
        ],
      },
      {
        id: 'ss4',
        type: 'mcq',
        category: 'Space Travel',
        text: 'What was the first artificial satellite launched into orbit?',
        options: [
          { id: 'a', text: 'Apollo 11' },
          { id: 'b', text: 'Hubble' },
          { id: 'c', text: 'Sputnik 1' },
          { id: 'd', text: 'Voyager 1' },
        ],
        correctOptionId: 'c',
      },
      {
        id: 'ss5',
        type: 'mcq',
        category: 'Universe',
        text: 'What is a light-year a measure of?',
        options: [
          { id: 'a', text: 'Time' },
          { id: 'b', text: 'Speed of light' },
          { id: 'c', text: 'Distance' },
          { id: 'd', text: 'Brightness of a star' },
        ],
        correctOptionId: 'c',
      },
    ],
  },
];
